### ISSUE TITLE
loading the Incenteev\HashedAssetBundle\IncenteevHashedAssetBundle class

### ISSUE THREAD

**Issue by rino1** [Incenteev/hashed-asset-bundle#24]
```
$ tree
├── composer.json
└── test.php

$ cat composer.json 
{
    "name": "my/package",
    "require": {
        "incenteev/hashed-asset-bundle": "*"
    }
}

$ cat test.php 
<?php
include 'vendor/autoload.php';
new Incenteev\HashedAssetBundle\IncenteevHashedAssetBundle;

$ php test.php 
PHP Warning:  include(): Failed opening 'vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in test.php on line 2
PHP Fatal error:  Uncaught Error: Class "Incenteev\HashedAssetBundle\IncenteevHashedAssetBundle" not found in test.php:3
```

Why?

Maybe we should give the command

```
$ composer install
```

but, if the my/package package were in turn required by another package, it would encourage duplication of the vendor directory.

Dear @stof you said it sex https://github.com/composer/composer/discussions/11403#discussioncomment-5453127 (if necessary reread the whole discussion).

So what should be done?

**Comment by stof** [comment]
If you don't run `composer install`, the dependency won't be installed. Here, you don't even have a `vendor/autoload.php` file.

> but, if the my/package package were in turn required by another package, it would encourage duplication of the vendor directory.

when working on a package, you should install its dependencies with `composer install`. But the `vendor` folder should be ignored from git so that it is not included in the package (and so not present when installing that package as a dependency instead of being the root package on which you work).

**Comment by rino1** [comment]
But what if it's a local repository?

https://github.com/composer/composer/discussions/11403#discussioncomment-5465545
```
    "repositories": {
        "one": {
            "type": "path",
            "url": "$PWD/one"
        },
        "two": {
            "type": "path",
            "url": "$PWD/two"
        }
    }
 ```

**Comment by stof** [comment]
I'm closing this as there is no issue in this bundle. If you don't actually install the bundle, it is totally expected that you cannot use it.

**Comment by rino1** [comment]
OK, but my observation remains a bit pending...

**Comment by stof** [comment]
I answered in the composer discussion, which is a better place to discuss a composer-related topic that is not specific to this package at all.
