### ISSUE TITLE
Enabling caching?

### ISSUE THREAD

**Issue by TiGR** [Incenteev/hashed-asset-bundle#6]
It is not really clear from the docs how can I make this bundle cache hashes. And how to make hashes built up during cache warmup. I see that all code is there, but enabling all this looks like quite tedious task with a lot of config hacking.

Is there an example how can I enable caching?

**Comment by TiGR** [comment]
Or it works by default on production environment only?

**Comment by stof** [comment]
it is cached automatically when the kernel is in non-debug mode (so this is the case in prod).
